apiVersion: skaffold/v4beta13
kind: Config

build:
  artifacts:
    - image: myapp
      jib:
        args:
          - -DskipTests
      sync:
        auto: true

manifests:
  rawYaml:
    - k8s/postgres.yaml
    - k8s/app.yaml
    -
deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: myapp
    port: 8080
    localPort: 8080